- Developer & Guides:
    - Trash Guides:
        - abbr: TG
          href: https://trash-guides.info/
    - Servarr Wiki:
        - abbr: SW
          href: https://wiki.servarr.com/
    - Homepage Docs:
        - abbr: HD
          href: https://gethomepage.dev/
    - GitHub Repository:
        - abbr: GH
          href: https://github.com/automation-avenue/arr-new
